#!/bin/bash

branch_name=$(git symbolic-ref --short HEAD)

# Extract the ticket number from the branch name using a regex pattern
ticket_number=$(echo "$branch_name" | grep -oE 'MB-[0-9]+')

# Get the commit message from the temporary commit message file created by Git
commit_message_file=$(mktemp)
trap 'rm -f "$commit_message_file"' EXIT

# Read the commit message from the temporary file
cat > "$commit_message_file"

# If the ticket number was found in the branch name, modify the commit message
if [[ "$ticket_number" ]]; then
  #sed -i '' "1s/^/$ticket_number - /" "$commit_message_file"
  commit_msg_file=$1
  echo "$ticket_number - $(cat $commit_msg_file)" > $commit_msg_file
fi

# Continue with the commit process
exit 0
